# Generated by Django 6.0.3 on 2026-04-07 06:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_passwordresettoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwordresettoken",
            name="token",
            field=models.CharField(default=uuid.uuid4, max_length=100, unique=True),
        ),
    ]
