# Generated by Django 6.0.3 on 2026-04-12 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_passwordresettoken_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="messenger_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
