# Generated by Django 6.0.3 on 2026-04-09 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="owner_fb_account_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
