# Generated by Django 6.0.3 on 2026-04-09 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0002_item_owner_fb_account_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="owner_fb_account_url",
            field=models.URLField(default="https://facebook.com/"),
        ),
    ]
