# Generated by Django 6.0.3 on 2026-04-10 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0003_alter_item_owner_fb_account_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="status",
            field=models.CharField(
                choices=[("lost", "Lost"), ("pending", "Pending"), ("found", "Found")],
                default="lost",
                max_length=10,
            ),
        ),
    ]
