# Generated by Django 6.0.3 on 2026-04-10 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0004_item_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="status",
            field=models.CharField(
                choices=[("lost", "Lost"), ("pending", "Pending"), ("found", "Found")],
                default="found",
                max_length=10,
            ),
        ),
    ]
