# Generated by Django 6.0.3 on 2026-04-10 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0002_report_landmark_image_url_and_landmark_blank"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="is_resolved",
            field=models.BooleanField(default=False),
        ),
    ]
